XXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX
XXXXXXXXX XXXXX
XXXXXX
XXXXXX
    XXXXX XXXXXXXXXXXXXXXXX
    XXXXXXXXXXX XXXXXXXXXXXXX
XXXXXXX
XXXXXX
    XXXX XXXX XXXX XXXXX XXX XXXX XX XXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX

    XXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXX X
            XX XXXXXXXXXX XXX XXX X  XX XXXXXX XXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            X
        XX

        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXX X
            XXX XXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXX X XXXXXXXX X XXXX
        XX
    XXXXXXXXX
XXXXXXX
XXXXXXX
