# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-22 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_foreignkeymodel2'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestMethodModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.BasicModel')),
            ],
        ),
    ]
