# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-22 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_testmethodmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmethodmodel',
            name='text',
            field=models.CharField(max_length=243),
        ),
    ]
