# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-28 02:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_auto_20180322_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreignkeymodel2',
            name='text',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.BasicModel'),
        ),
    ]
