# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-08 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_auto_20180328_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, '以支付'), (1, '为支付')])),
            ],
        ),
    ]
