# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-16 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_testpropertymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestAdminModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.URLField()),
            ],
        ),
    ]
