# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-25 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0011_auto_20180423_1700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mymodel',
            options={'verbose_name_plural': '简单的MyModel'},
        ),
        migrations.AlterModelOptions(
            name='testfiltermodel',
            options={'verbose_name_plural': '测试过滤的Model'},
        ),
        migrations.AlterModelOptions(
            name='testfilterthrough',
            options={'verbose_name_plural': '测试过滤的中间键through'},
        ),
        migrations.AddField(
            model_name='testnullmodel',
            name='can_null_blank_integer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testfiltermodel',
            name='many',
            field=models.ManyToManyField(blank=True, to='testapp.MyModel'),
        ),
    ]
