# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-07 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0013_testonetoonefield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testonetoonefield',
            name='text',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.BasicModel'),
        ),
    ]
