# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-07 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0015_testfiltermodel2'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestMethodTriggerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
    ]
