# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-19 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0016_testmethodtriggermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestUniqueModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(max_length=42, unique=True)),
                ('text2', models.CharField(blank=True, max_length=42, unique=True)),
                ('text3', models.CharField(max_length=42, null=True, unique=True)),
                ('text4', models.CharField(blank=True, max_length=42, null=True, unique=True)),
            ],
        ),
    ]
