# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-29 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0017_testuniquemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDecimalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deci', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
