# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-27 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0018_testdecimalmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testdecimalmodel',
            options={'verbose_name_plural': '测试DecimalField'},
        ),
        migrations.AlterField(
            model_name='testdecimalmodel',
            name='deci',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4),
        ),
    ]
