# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-05 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0021_student_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('teachers', models.ManyToManyField(to='testapp.Teacher')),
            ],
        ),
    ]
