# Generated by Django 2.1.4 on 2018-12-20 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0022_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreignkeymodel2',
            name='text',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testapp.BasicModel'),
        ),
        migrations.AlterField(
            model_name='testfiltermodel',
            name='text',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testapp.BasicModel'),
        ),
    ]
