# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-11 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0023_auto_20181220_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_type', models.CharField(choices=[('类型1', '类型1'), ('类型2', '类型2'), ('类型3', '类型3')], max_length=5, verbose_name='类型')),
            ],
        ),
    ]
