# Generated by Django 2.1.5 on 2019-02-26 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0026_testadminpermissionmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testadminpermissionmodel',
            options={'verbose_name_plural': '测试admin的权限'},
        ),
    ]
