# Generated by Django 2.1.5 on 2019-04-02 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0027_auto_20190226_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='datetimemodel',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(days=1)),
        ),
    ]
