# Generated by Django 2.1.5 on 2019-07-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0029_testautonow'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateTimeOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(null=True)),
            ],
        ),
    ]
