# Generated by Django 2.1.5 on 2019-08-19 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0031_auto_20190819_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('testapp.basicmodel',),
        ),
    ]
