# Generated by Django 2.2.5 on 2019-10-17 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0032_testmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel2',
            fields=[
                ('basicmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testapp.BasicModel')),
            ],
            bases=('testapp.basicmodel',),
        ),
    ]
