# Generated by Django 2.2 on 2020-03-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0033_testmodel2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Database2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=31)),
            ],
        ),
    ]
