XXXXXXXXX XXXXX
BBBB BBBBBBBBBBBBB
XXXXXX
  XXXXXX
    XXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
  XXXXXXX
  XXXXXX
    XXXXXXXXXXXXX
    XXXXXXXXXX XXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXX BBBBBBBBBBBB BBBBBBBBB BBBBBBBBBBBBXXXX
      XXXXX BBBBBBBBBBBB BBBBBBBBB BBBBBBBBBBBB
    XXXX XXXXXXXXXXXXXX
      BBBB BBBBBBBBBBBBBBBBBBBBBBBBBB
        XXXXXXXXXXXXXXX
        XXXXXXX
        XXXXXXX
        XXXXXXX
      BBBBBBB
      XXXXXXXXXXXXXXX
        XXXBBBBBBBBXXXX
        XXXBBBBBBBBXXXX
        XXXBBBBBBBBXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      BBBBBBBB BB BBBB
        XXXXXXXXXXXXXXX
        XXXXXXX
        XXXXXXX
        XXXXXXX
      BBBBBBBB BB BBBB
        XXXXXXXXXXXXXXX
        XXXXXXX
        XXXXXXX
        XXXXXXX
    XXXXXXXX
      XXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXX
      XX XXXXXXXXXXXXXXFFFFXX
      XXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXFFFFX
      XXXXXXXXXXXXXFFFFX
    XXXXXXXXX
    XXXXXXXX
      XX XXXXXXXXXXXX
      BBBBBBBBBB BBB
      XXXXXXXXXXXXXXXX
      XX XXXXXXXXXXXXXXXX  XXXXXXX
      XX XXXXXXXXXXXXXXFFFFXX  XXXXXXX
      XX XXXXXXXXXXXXXXXX  XXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXX
      XXXXXXXXXXXXXFFFFX
      XXXXXXXXXXXXXFFFFX
      BBBBBBBBBBBBB
    XXXXXXXXX
  XXXXXXX
XXXXXXX
